export const IMAGES = {
  gpt: new URL('./gpt-4o.webp', import.meta.url).href,
  claude: new URL('./claude-sonnet.webp', import.meta.url).href,
  logoGreen: new URL('./logo-green.png', import.meta.url).href,
  logoLight: new URL('./logo-light.png', import.meta.url).href,
  logoDark: new URL('./logo-dark.png', import.meta.url).href,
  deepSeek: new URL('./deepseek.webp', import.meta.url).href,
  chatGpt: new URL('./svgs/chatgpt.svg', import.meta.url).href,
  gemini: new URL('./svgs/gemini.svg', import.meta.url).href,
  anthropic: new URL('./svgs/anthropic.svg', import.meta.url).href,
  avatar1: new URL('./avatar1.png', import.meta.url).href,
  avatar2: new URL('./avatar2.png', import.meta.url).href,
  avatar3: new URL('./avatar3.png', import.meta.url).href,
  chat: new URL('./svgs/chat-2.svg', import.meta.url).href,
  sparkles: new URL('./svgs/sparkles.svg', import.meta.url).href,
  infinity: new URL('./svgs/infinity.svg', import.meta.url).href,
  webSearch: new URL('./svgs/web-search-2.svg', import.meta.url).href,
  file: new URL('./svgs/file.svg', import.meta.url).href,
  image: new URL('./svgs/image-2.svg', import.meta.url).href,
  paypal: new URL('./svgs/paypal.svg', import.meta.url).href,
  visa: new URL('./svgs/visa.svg', import.meta.url).href,
  mastercard: new URL('./svgs/mastercard.svg', import.meta.url).href,
  discover: new URL('./svgs/discover.svg', import.meta.url).href,
  americanExpress: new URL('./svgs/amex.svg', import.meta.url).href,
  jcb: new URL('./svgs/jcb.svg', import.meta.url).href,
} as const;
